spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/Feedback
spring.datasource.username=postgres
spring.datasource.password=P0pUeqO5iHbuUWL2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true